Repository ruoyuwang1995nya/pfd-kit, pull requests merged in 2024-11, with the labels that each got.

#76 fix: issues with multi-task training
  docs/conf.py
  docs/development/api.md
  docs/development/modules.rst
  docs/development/pfd.entrypoint.rst
  docs/development/pfd.exploration.converge.rst
  docs/development/pfd.exploration.inference.rst
  docs/development/pfd.exploration.render.rst
  docs/development/pfd.exploration.rst
  docs/development/pfd.exploration.scheduler.rst
  docs/development/pfd.exploration.selector.rst
  docs/development/pfd.exploration.task.calypso.rst
  docs/development/pfd.exploration.task.lmp.rst
  docs/development/pfd.exploration.task.rst
  docs/development/pfd.flow.rst
  docs/development/pfd.fp.rst
  docs/development/pfd.op.rst
  docs/development/pfd.rst
  docs/development/pfd.superop.rst
  docs/development/pfd.train.rst
  docs/development/pfd.utils.rst
  docs/index.rst
  pfd/entrypoint/args.py
  pfd/entrypoint/main.py
  pfd/entrypoint/submit.py
  pfd/exploration/inference/eval_dp.py
  pfd/exploration/inference/eval_model.py
  pfd/flow/fine_tune.py
  pfd/op/inference.py
  pfd/op/model_test.py
  pfd/superop/exploration_finetune_loop.py
Labels: bug, documentation

#78 fix: modify doc homepage to make the scientific purpose and advantages more clearly.
  docs/index.rst
Labels: documentation

#88 feat: add recursive fine-tune
  docs/basics/getting-started.md
  docs/basics/overview.md
  pfd/entrypoint/args.py
  pfd/entrypoint/submit.py
  pfd/exploration/converge/energy_conv_filter.py
  pfd/exploration/scheduler/sheduler.py
  pfd/op/stage.py
  pfd/superop/exploration_dist_loop.py
  pfd/superop/exploration_finetune_loop.py
Labels: bug, enhancement

#96 fix: correct rmse calculator
  pfd/entrypoint/args.py
  pfd/exploration/inference/eval_model.py
  tests/test_test_reports.py
Labels: bug
